[workspace]
authors = ["Liangliang Zhu <shinyypig@gmail.com>"]
channels = ["conda-forge"]
name = "Videos"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
manim = ">=0.19.0,<0.20"
jupyter = ">=1.1.1,<2"
pip = ">=25.2,<26"
